plugins {
    id 'com.android.application'
}

def releaseKeystorePath = System.getenv('RELEASE_KEYSTORE_PATH')

android {
    namespace 'ru.tubetv.app'
    compileSdk 36

    defaultConfig {
        applicationId 'ru.tubetv.app'
        minSdk 23
        targetSdk 35
        versionCode 25
        versionName '0.5.17'
        resourceConfigurations += ['ru']
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    signingConfigs {
        if (releaseKeystorePath) {
            release {
                storeFile file(releaseKeystorePath)
                storePassword System.getenv('RELEASE_STORE_PASSWORD')
                keyAlias System.getenv('RELEASE_KEY_ALIAS')
                keyPassword System.getenv('RELEASE_KEY_PASSWORD')
            }
        }
    }

    buildTypes {
        release {
            if (releaseKeystorePath) {
                signingConfig signingConfigs.release
            }
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    packaging {
        resources {
            excludes += [
                    '/DebugProbesKt.bin',
                    '/kotlin/**',
                    '/META-INF/*.version',
                    '/META-INF/versions/**',
                    '/META-INF/version-control-info.textproto'
            ]
        }
    }
}

dependencies {
    implementation 'androidx.core:core:1.17.0'
    implementation 'androidx.media3:media3-exoplayer:1.10.1'
    implementation 'androidx.media3:media3-exoplayer-hls:1.10.1'
    implementation 'androidx.media3:media3-exoplayer-dash:1.10.1'
}
